### ISSUE TITLE
S3 Creation Date Differs By Region

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#1081]
### Describe the bug

CreationDate in the console is the same value you would get if you did `aws s3 ls --region us-east-1` while the CreationDate you get in any other region is the last modified date.

### Expected Behavior

Return a consistent Creation Date

### Steps to Reproduce

`aws s3 ls --region us-east-1` 
`aws s3 ls --region us-east-2` 

### Provider and CloudQuery version

all

**Comment by erezrokah** [comment]
![94b6e9b5b7c9c2afdada75b063e5ef96](https://user-images.githubusercontent.com/26760571/174784028-d50d84ae-c9ff-46ef-a76f-b69e72bd4709.gif)
