### ISSUE TITLE
Default Profile AWS Config

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#1186]
### Describe the bug

If you use a profile named `default` CloudQuery will not assume the role correctly. 

### Expected Behavior

Use profile and assume role

### Steps to Reproduce

use sso profile named [default]

### Provider and CloudQuery version

all?

**Comment by candiduslynx** [comment]
Digging deeper into the configuration it appeared that the `~/.aws/credentials` file with already revoked static credenttials got in the way. Once removed everything worked as expected.
