### ISSUE TITLE
Lambda table not been populated when using ViewOnlyAccess

### ISSUE THREAD

**Issue by maxboaventura** [cloudquery/cq-provider-aws#1191]
### Describe the bug

Although "Lambda:List*" is present, no error is received and Lambda tables are completely empty when running Cloudquery with ViewOnlyAccess set of permissions.

### Expected Behavior

Populate the tables with the data we can get using the "lambda:List*" permissions present on the ViewOnlyAccess

### Steps to Reproduce

Execute Cloudquery with ViewOnlyAccess set of permissions.

### Provider and CloudQuery version

AWS

**Comment by bbernays** [comment]
This functionality has been released in [`v0.12.28`](https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.12.28)
