### ISSUE TITLE
Support AWS Glue services

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cq-provider-aws#1243]
### Describe the resource.

https://docs.aws.amazon.com/sdk-for-go/api/service/glue/

### Use Case

Glue is a large service with multiple components, so this might need to be split up. We need to be able to catalog Glue resources.

Also AWS is deprecating Glue 1.0 so we need to be able to know what teams are running Glue 1.0 in our org so we can migrate

### Additional context

AWS Glue has the following resources that need to be implemented:

- [x] #1384
- [x] #1299
- [x] #1298
- [x] #1328
  - [x] #1330
  - [x] #1368
- [x] #1329
- [x] #1358
- [x] #1346
- [x] #1364
- [x] #1324
  - [x] AWS::Glue::Schema
  - [x] #1380
  - [x] AWS::Glue::SchemaVersionMetadata
- [x] #1381
- [x] #1311
- [x] #1302

**Comment by bbernays** [comment]
- [ ] AWS::Glue::Classifier
- [ ] AWS::Glue::Connection
- [ ] AWS::Glue::Crawler
- [ ] AWS::Glue::Database
- [ ] AWS::Glue::DataCatalogEncryptionSettings
- [ ] AWS::Glue::DevEndpoint
- [ ] AWS::Glue::Job
- [ ] AWS::Glue::MLTransform
- [ ] AWS::Glue::Partition
- [ ] AWS::Glue::Registry
- [ ] AWS::Glue::Schema
- [ ] AWS::Glue::SchemaVersion
- [ ] AWS::Glue::SchemaVersionMetadata
- [ ] AWS::Glue::SecurityConfiguration
- [ ] AWS::Glue::Table
- [ ] AWS::Glue::Trigger
- [ ] AWS::Glue::Workflow
