### ISSUE TITLE
CloudWatch Logs Support

### ISSUE THREAD

**Issue by deep-spaced** [cloudquery/cq-provider-aws#1296]
### Describe the resource.

https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchlogs/

### Use Case

I am gathering information about the current account workload and need to know how many log groups and streams are set up. Thank you!

### Additional context

The following should be implemented to retrieve information about the log groups and logs in the account:

- [x] #1306
- [x] #1307

**Comment by bbernays** [comment]
@deep-spaced - Do you think that we should support fetching individual cloudwatch log streams or just the groups?

**Comment by deep-spaced** [comment]
@bbernays My use case is to figure out all the different pieces of the workload in the account which includes logs. My initial thought was to include streams but the first time I pulled logs AND streams from my test account, I pulled 80k streams. This is just too much noise since I don't care about the individual days, just that there is cloud logging occurring. 

In other words, knowing that there are 8 log groups is more important that knowing there are 80 log streams (one stream for each of the 10 prior days using daily log rotation). 

Thank you!

**Comment by bbernays** [comment]
Completely agree. Especially for users that use Lambda, where each ephemeral container creates its own log stream. So I will close the issue for adding cloudwatch streams

**Comment by deep-spaced** [comment]
@bbernays saw your PR in #1321, should I close my PR #1317?

**Comment by bbernays** [comment]
if you want to incorporate the `gen.hcl` file that enables automating the generation of the resource via [this](https://github.com/cloudquery/cq-gen) I am more than happy to close my branch!

**Comment by deep-spaced** [comment]
That's pretty cool, @bbernays! Updated with `gen.hcl`.
