### ISSUE TITLE
ECR repositories have tags but they aren't pulled

### ISSUE THREAD

**Issue by Barneyjm** [cloudquery/cq-provider-aws#1367]
### Describe the bug

according to the Go SDK, tags can be pulled for ECR but they're not pulled by the CQ resource. 

https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/#ECR.ListTagsForResource

### Expected Behavior

tags should be included in the aws_ecr_repositories table

### Steps to Reproduce

select tags from aws_ecr_repositories; 

db query error: pq: column "tags" does not exist

https://github.com/cloudquery/cq-provider-aws/blob/main/resources/services/ecr/repositories.go

### Possible Solution

https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/#ECR.ListTagsForResource

implemented here https://github.com/cloudquery/cq-provider-aws/blob/main/resources/services/ecr/repositories.go

### Provider and CloudQuery version

cloudquery version v0.31.8. provider=aws version=v0.13.3

**Comment by bbernays** [comment]
Thank you for opening this issue! The next release should include tag support for ECR repos!
