### ISSUE TITLE
IAM resources aren't being captured

### ISSUE THREAD

**Issue by nick123pig** [cloudquery/cq-provider-aws#15]
I'm doing some regression testing between v0.8.6 and v0.11.6 and it seems like IAM resources aren't being captured (with iam.groups being the lone exception). 

```
$ cat cloudquery.log | grep iam
{"level":"info","@module":"aws","account_id":"965473048149","count":0,"resource":"iam.groups","timestamp":"2021-03-14T06:33:25.492Z","time":"2021-03-14T06:33:25Z","message":"Fetched resources"}
```

```
$ cat config.yml | grep iam
        - name: iam.groups
        - name: iam.password_policies
        - name: iam.policies
        - name: iam.roles
        - name: iam.users
        - name: iam.virtual_mfa_devices
```

**Comment by yevgenypats** [comment]
@nick123pig Thanks for bringing this up! I accidentally introduced this bug 2 releases ago when I added better concurrency support. Fixed in https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.2.7
