### ISSUE TITLE
Verbose logging does not get passed through to aws provider

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cq-provider-aws#17]
If `-v` or `--verbose` are provided, still only "INFO" level logs are output from the aws provider. Also it appears that a different logging package is being used between the core cli and the providers?

**Comment by roneli** [comment]
There was a bug in the provider sdk that wasn't passing the log correctly to the main process. (this doesn't work in debug mode). I am going to double check this again. This was fixed in CQ 0.13.x and providers using sdk 0.2.0+
