### ISSUE TITLE
Resource data for AWS SQS

### ISSUE THREAD

**Issue by hobietje** [cloudquery/cq-provider-aws#202]
We would like to run security audits of AWS SQS queues, but the resource data is currently missing.  Eg. queue is public due to resource policy, queue doesn't have encryption-at-rest, etc.

**Comment by roneli** [comment]
Hi, @hobietje, thanks for the issue, we will start adding this soon.

Add support for [SQS ](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_Operations.html) Resource
Add The following read actions:
- [ ] ListQueues
- [ ] GetQueueAttributes
- [ ] ListQueueTags
