### ISSUE TITLE
Error while fetching resources

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#23]
Since 24th of March we've seen errors while fetch AWS resources.

I saw https://github.com/cloudquery/cq-provider-aws/issues/12 and tried it but I'm getting a similar error but not the same.

```
Error: rpc error: code = Unknown desc = operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 0, RequestID: , canceled, context deadline exceeded
```

Do you know what might be happening?

**Comment by yevgenypats** [comment]
Thanks for bringing it up. We've added support for context,timeouts,etc... but apparently it didn't work as expected. I'm going to push a fix shortly.

**Comment by yevgenypats** [comment]
This should fix it hopefully (removed timeout by default) and I think there was some bug with how  Golang context where passed. https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.2.18

**Comment by xino12** [comment]
it does :D 🙇🏼
