### ISSUE TITLE
Disabled regions detection is using hardcoded region "us-east-1" that could be a disabled region in some configurations

### ISSUE THREAD

**Issue by Rackme** [cloudquery/cq-provider-aws#242]
### Describe the Bug
In some configurations, accounts could be regional and thus could not use the region "us-east-1", disabled by Service control policies (SCPs).

![screenshot_318](https://user-images.githubusercontent.com/13887304/140044259-7be024e4-5f97-4f6f-a681-a14fe5a49b53.png)

### Expected Behavior
If regions are specified in the config.hcl, the use of _DescribeRegions_ to detect disable regions should use one of them. 

### CloudQuery Version
cq-provider-aws v0.6.0

### Debug Output

![cloudquery-AWS-disabledRegion](https://user-images.githubusercontent.com/13887304/140044177-1b2d75d5-850d-4044-a4e9-a15935329d94.png)

### Steps to Reproduce
Use of the following configuration with an account limited to these regions :
```
provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
    //accounts "<YOUR ID>" {
    // Optional. Role ARN we want to assume when accessing this account
    // role_arn = <YOUR_ROLE_ARN>
    // }
    regions = ["eu-west-3", "eu-central-1"]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = true
  }
```

### Additionnal content
I will probably do a PR for this one. I might have the time for it.

### References
https://github.com/cloudquery/cq-provider-aws/issues/39

**Comment by roneli** [comment]
Hi @Rackme, thanks for the issue, yes that makes sense we can either make it configurable to disable checking disabled regions, or create a fallback in this case to find disabled regions with regions defined from the list of regions given.

Tell me if you require any assistance with the PR.
