### ISSUE TITLE
Support for Route 53 Domains

### ISSUE THREAD

**Issue by hobietje** [cloudquery/cq-provider-aws#248]
### New Resource

[Route 53 Domains](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonroute53domains.html)

* ListDomains
* ListTagsForDomain
* GetDomainDetail

### Use Case

* Verify TransferLock is enabled
* Verify AutoRenew is enabled
* Verify domain registrations are not Expired
* Verify admin/tech/billing contacts are up to date
* Verify admin privacy is enabled
* Verify DNSSEC configuration

**Comment by roneli** [comment]
Hi @hobietje, we released a new version [v0.6.3](https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.6.3) supporting this resource
