### ISSUE TITLE
Cloudtrail Support

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#258]
### Describe the Bug

When a cloudtrail trail has no tags it skips over it.

### Expected Behavior

CQ should store the trail even if there are no tags attached to it

### CloudQuery Provider Version 

```
version=v0.6.3
```

### Steps to Reproduce
```
cloudquery fetch
```

```
  resources = [
    "cloudtrail.trails",
  ]
```
### Additional Context

ensure there is a trail with no tags in your aws account

**Comment by roneli** [comment]
Duplicate for #253
