### ISSUE TITLE
AWS Regions Enabled

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#263]
### New Resource

Now that [AWS Regions](https://aws.amazon.com/blogs/security/setting-permissions-to-enable-accounts-for-upcoming-aws-regions/) are being brought online in disabled states we should be saving the state of every region in our asset inventory

### Use Case

For compliance validation, we can skip all regions that are disabled rather than inferring lack of data to mean an unknown state

### Additional context

All information can be grabbed from the ec2 DescribeRegions endpoint:

```
aws ec2 describe-regions --all-regions
```

**Comment by roneli** [comment]
Was added in v0.7.0
