### ISSUE TITLE
Reduce Complexity of Security Group Rules

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#275]
### Improvement

It seems like there is an opportunity to reduce complexity in terms of number of tables required to fully define ec2 Security Groups. Currently there are 10 tables to fully define egress and ingress rules. These tables could be collapsed into 5 tables where we would just add a column to specify if it is an egress or ingress rule. The value is already returned from the `describe-security-group-rules` call in `IsEgress`

### Use Case

Reduce complexity when writing queries and just use `where` clauses rather than joins

**Comment by yevgenypats** [comment]
I suggest the following structure:

Changing from current 10 tables to 3 tables

two tables:
`aws_ec2_security_groups`
`aws_ec2_security_group_permissions`
`aws_ec2_security_group_ip_permissions_egresses`

all other tables will be collapsed to JSONs

**Comment by bbernays** [comment]
I worry about swinging too far in the direction of simplification for a couple of reasons:
1) We want to make the table structure familiar and accessible to those people that are comfortable with the SG API
2) If we make things JSON objects by the time you need to access prefix_lists or user_id_group_pairs the queries will get insanely complex
3) By combining egress and ingress ip permissions we can go from 11 --> 6
4) After that we can combine ip_ranges and ipv6_ranges and go from 6 --> 5


Here are the list of all of the SG tables:
```
aws_ec2_security_group_ip_permission_ip_ranges
aws_ec2_security_group_ip_permission_ipv6_ranges
aws_ec2_security_group_ip_permission_prefix_list_ids
aws_ec2_security_group_ip_permission_user_id_group_pairs
aws_ec2_security_group_ip_permissions
aws_ec2_security_group_ip_permissions_egress_ip_ranges
aws_ec2_security_group_ip_permissions_egress_ipv6_ranges
aws_ec2_security_group_ip_permissions_egress_prefix_list_ids
aws_ec2_security_group_ip_permissions_egress_user_group_pairs
aws_ec2_security_group_ip_permissions_egresses
aws_ec2_security_groups
```

trimmed down list:
```
aws_ec2_security_groups
aws_ec2_security_group_ip_permission_ip_ranges
aws_ec2_security_group_ip_permission_prefix_list_ids
aws_ec2_security_group_ip_permission_user_id_group_pairs
aws_ec2_security_group_ip_permissions
```

**Comment by yevgenypats** [comment]
I agree this is also a good alternative. One thing that bothers me is that I don't understand why in the API `aws_ec2_security_group_ip_permission_ip_ranges ` is a list ?

I don't see an ability to create multiple ip_ranges in the console
![image](https://user-images.githubusercontent.com/16490766/146634628-db3c1aa8-ec81-4703-8ef3-19ed3edb5fc4.png)

```
	// The IPv4 ranges.
	IpRanges []IpRange

	// [VPC only] The IPv6 ranges.
	Ipv6Ranges []Ipv6Range

	// [VPC only] The prefix list IDs.
	PrefixListIds []PrefixListId
```

Also 
```
aws_ec2_security_group_ip_permission_ip_ranges
aws_ec2_security_group_ip_permission_ipv6_ranges
aws_ec2_security_group_ip_permission_prefix_list_ids
```
are all basically tables with one attribute and description so I feel it wont be too complex.
Regarding `aws_ec2_security_group_ip_permission_user_id_group_pairs ` I agree this is a multi attribute table and prob better to keep it this way.

wdyt ?

**Comment by bbernays** [comment]
To me this indicates that they reserve the right in the future to support multiple IP addresses per rule, but have chosen to keep it singular at this time. I can think of a couple of other places where AWS does this. It is just part of their backwards compatibility guarantees... If we were to assume that the list/arrays were always of length 1 then we would have to fix/change our provider in the future if they switched... Unless we were able to get it in writing in public that it will always be a maximum of length 1
