### ISSUE TITLE
Config Status Support

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#276]
### New Resource
We need to record the status of Config Recorders. We currently support fetching the details of a config recorder (`DescribeConfigurationRecorders`), but we do not fetch the status which is available at  `DescribeConfigurationRecorderStatus`

### Use Case

AWS CIS Benchmarks require Config to be enabled. We cannot currently validate that benchmark without this data

**Comment by roneli** [comment]
Added in #301
