### ISSUE TITLE
S3 Bucket Encryption Rules

### ISSUE THREAD

**Issue by jtrogers** [cloudquery/cq-provider-aws#29]
It seems that fetch no longer updates the [aws_s3_bucket_encryption_rules](https://schema.cloudquery.io/tables/aws_s3_bucket_encryption_rules.html) table.  Is this feature no longer available?

**Comment by yevgenypats** [comment]
Hi @jtrogers , thanks for reporting! I think this a bug that was introduced after we released [v0.3.0](https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.0) with the [new SDK](https://www.cloudquery.io/blog/introducing-cloudquery-sdk). I'll fix this shortly.

**Comment by yevgenypats** [comment]
Released - https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.3
