### ISSUE TITLE
Feature request: Support All ECS Resources

### ISSUE THREAD

**Issue by eilonlotem** [cloudquery/cq-provider-aws#303]
### New Resource
ECS Instances, Tasks, Task Definitions

### Use Case
I want to get all ECS instances if it is an EC2, Container, or Farget, including their environment variables

### Additional context

Example of python code I wrote:
def get_ecs_assets(ecs_client):
    ecs_clusters = []
    paginator = ecs_client.get_paginator('list_clusters')
    page_iterator = paginator.paginate()

    for page in page_iterator:
        for cluster in page['clusterArns']:
            res = ecs_client.describe_clusters(clusters=[cluster])    
            ecs_clusters += res['clusters']
            
    for cluster in ecs_clusters:        
        cluster['EcsClusterTask'] = []
        tasks_arns = ecs_client.list_tasks(cluster=cluster['clusterArn'])['taskArns']
        
        if not tasks_arns:
            continue

        res = ecs_client.describe_tasks(
            cluster=cluster['clusterArn'],
            tasks=tasks_arns
        )

        for task in res['tasks']:
            task['task_definition'] = ecs_client.describe_task_definition(
                taskDefinition=task['taskDefinitionArn']
            )['taskDefinition']
            
            cluster['EcsClusterTask'].append(task)

    return {
        'EcsCluster': ecs_clusters
    }

**Comment by bbernays** [comment]
@eilonlotem- Thank you for your feature request! We have just merged support for ECS Tasks. We will release a new version this coming week. If you have any more issues or requests feel free to open a new issue!
