### ISSUE TITLE
Incorrect resource for ecr created by `gen config aws`

### ISSUE THREAD

**Issue by jtrogers** [cloudquery/cq-provider-aws#31]
`gen config aws` creates `config.yml` that includes the following line:
`        - name: ecr.images
`

`fetch` produces the following error:
> Error: rpc error: code = Unknown desc = plugin aws does not provide resource ecr.images

Should the resource generated be `ecr.repositories` instead of `ecr.images`?

**Comment by yevgenypats** [comment]
Solved https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.4
