### ISSUE TITLE
Elasticbeanstalk Application and Template Support

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#311]
### New Resource

[Elasticbeanstalk](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk#Client)

- [ ] `DescribeApplications`
- [ ] `DescribeApplicationsVersions`
- [ ] `DescribeConfigurationOptions`
- [ ] `DescribeConfigurationSettings`

**Comment by bbernays** [comment]
@erezrokah- I know you worked on some EB resources a couple of weeks ago, was this completed?

**Comment by erezrokah** [comment]
Yes! We can close this 👍  Was done as a part of https://github.com/cloudquery/cq-provider-aws/issues/621
