### ISSUE TITLE
Incorrect resource for redshift created by `gen config aws`

### ISSUE THREAD

**Issue by jtrogers** [cloudquery/cq-provider-aws#32]
`gen config aws` creates `config.yml` that includes the following line:

`    - name: redshift.cluster_subnet_groups
`

`fetch` produces the following error:
> Error: rpc error: code = Unknown desc = plugin aws does not provide resource redshift.cluster_subnet_groups

Should the resource generated be `subnet_groups` instead of `cluster_subnet_groups`?

**Comment by yevgenypats** [comment]
Thanks. Solved with https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.4
