### ISSUE TITLE
Incorrect resource for cloudwatchlogs created by `gen config aws`

### ISSUE THREAD

**Issue by jtrogers** [cloudquery/cq-provider-aws#33]
`gen config aws` creates `config.yml` that includes the following line:

`        - name: cloudwatchlogs.metric_filters
`

`fetch` produces the following error:

> Error: rpc error: code = Unknown desc = plugin aws does not provide resource cloudwatchlogs.metric_filters

Should the resource generated be `filters` instead of `metric_filters`?

**Comment by yevgenypats** [comment]
Thanks. Solved with https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.4
