### ISSUE TITLE
Error on assuming role with required MFA

### ISSUE THREAD

**Issue by raphlcx** [cloudquery/cq-provider-aws#35]
## Summary

Hi, I'm getting an error when attempting to assume into a role which requires MFA.

## Reproduction scenario

First, create an AWS IAM role and require MFA when assuming into the role. [This guide](https://aws.amazon.com/blogs/security/how-do-i-protect-cross-account-access-using-mfa-2/) might help.

Then, in `~/.aws/config`:

```
[profile aaa]
aws_access_key_id = ...
aws_secret_access_key = ...

[profile bbb]
region = us-east-1
role_arn = arn:aws:iam::xxx:role/the-role-to-assume
mfa_serial = arn:aws:iam::xxx:mfa/my-user
source_profile = aaa
```

Execute the command:

```
AWS_PROFILE=bbb cloudquery fetch --dsn '...'
```

Error:

```
Error: rpc error: code = Unknown desc = assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

**Comment by raphlcx** [comment]
Hi @zagronitay , was this resolved? Or any workarounds if otherwise?

**Comment by yevgenypats** [comment]
Hi @raphlcx, This is in PR right now - https://github.com/cloudquery/cq-provider-aws/pull/351/files

**Comment by raphlcx** [comment]
> Hi @raphlcx, This is in PR right now - https://github.com/cloudquery/cq-provider-aws/pull/351/files

Noted, thanks!
