### ISSUE TITLE
Error assuming role

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#39]
I have setup the AWS_DEFAULT_REGION to aws-global in my ingestion jobs and it was working properly but now I see this error in the logs:

```
Error: rpc error: code = Unknown desc = operation error EC2: DescribeRegions, exceeded maximum number of attempts, 10, https response error StatusCode: 0, RequestID: , request send failed, Post "https://ec2.aws-global.amazonaws.com/": dial tcp: lookup ec2.aws-global.amazonaws.com on 10.131.230.10:53: no such host
```

Are you aware whether something in AWS side has changed? I've looked for documentation and I can't see anything and AFAIK we're still assuming roles as we did in the past for other tools we use.

**Comment by xino12** [comment]
I thought it might be related to https://github.com/cloudquery/cq-provider-aws/issues/12 but when that happened I was able to fix it by setting that env var, now the problem seems like something else, probably something changed in the AWS sdk ?

**Comment by xino12** [comment]
It seems that we're forced to use the same endpoint for STS and EC2, in our case we would like to be able to use the regional endpoint for EC2(as it seems that the global endpoint is not available) and use the global endpoint for STS service. Could we add a configuration parameter maybe?

**Comment by yevgenypats** [comment]
Should be fixed in https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.3.7

**Comment by xino12** [comment]
🏆 thanks 🙇🏼
