### ISSUE TITLE
Adding new resources for security checks

### ISSUE THREAD

**Issue by Rackme** [cloudquery/cq-provider-aws#4]
There is a lot of security checks that currently cannot be performed in cloudquery as their configuration or some services are missing.
To integrate these checks, the following resources could be added over time :

- [x] CloudFront Distribution
- [x] CloudFront Policies
- [x] VPC endpoint 
- [x] VPC VPN (transit gateway)
- [x] Route 53
- [x] ELBv1
- [x] IAM Identity Provider
- [x] IAM policies (user inline policy / group policy / role policy)
- [x] Lambda functions
- [x] Api Gateway (URL & routes)
- [x] Api Gateway (relations (CF -> lambda))

I will add further information asap.

**Comment by roneli** [comment]
Hi @Rackme we added most resources, if I am not correct all exists in latest version except API gateway v1 and lambda we will release a new version soon. Tell me if any more resources are required. We are gradually adding them all, but it will help prioritize.

**Comment by Rackme** [comment]
Great, I wanted to see the content of each services you added, however with the new configuration I get the following error :

**Config.hcl extract :**
```
// All Provider Configurations

provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
     accounts "profile_tst_orga"{ }
    // Optional. by default assumes all regions
    // regions = ["us-east-1", "us-west-2"]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = true

    max_retries = 5
    //max_backoff = 30 
  }

```

**Result :**
```
root@a1d62cb9aa12:~# ./cloudquery_Linux_x86_64 fetch --enable-console-log
1:27PM INF logging configured consoleLog=true fileLogging=true fileName=cloudquery.log jsonLogOutput=false logDirectory=. maxAgeInDays=3 maxBackups=3 maxSizeMB=30 verbose=false
1:27PM INF Initializing required providers
1:27PM INF Initializing provider name=aws version=latest
1:27PM INF requesting provider to configure provider=aws version=v0.4.3
1:27PM INF 2021/05/27 13:27:27 Failed to load configuration: config.json:1,14-30: Extraneous JSON object property; No argument or block type is named "profile_tst_orga". @module=aws timestamp=2021-05-27T13:27:27.353Z
1:27PM ERR failed to configure provider error="rpc error: code = Unavailable desc = transport is closing" provider=aws
```

Am I missing somethings with the new configuration ?

**Comment by roneli** [comment]
Fixed in #80 the error makes sense since we didn't define "id" as a label for the account, and this only happened because we missed  a "," before the label. Merged it will release a new version very soon.

**Comment by roneli** [comment]
`// All Provider Configurations

provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
     accounts  {
        label = "profile_tst_orga"
     }
    // Optional. by default assumes all regions
    // regions = ["us-east-1", "us-west-2"]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = true

    max_retries = 5
    //max_backoff = 30 
  }
`

**Comment by Rackme** [comment]
Thanks for the fix. The only error I got was with the "route53.hosted_zones" service :

```
10:15AM DBG resolving table relation @module=aws account_id=12345678912 relation=aws_route53_hosted_zone_resource_record_sets table=aws_route53_hosted_zones timestamp=2021-05-28T10:15:41.788Z
10:15AM DBG panic: runtime error: invalid memory address or nil pointer dereference
10:15AM DBG [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3d0901c]
10:15AM DBG
10:15AM DBG goroutine 4277 [running]:
10:15AM DBG github.com/cloudquery/cq-provider-aws/resources.fetchRoute53HostedZones.func1(0xc0004755c0, 0x6, 0xc, 0x0, 0x0)
10:15AM DBG     /home/runner/work/cq-provider-aws/cq-provider-aws/resources/route53_hosted_zones.go:276 +0x6fc
10:15AM DBG github.com/cloudquery/cq-provider-aws/resources.fetchRoute53HostedZones(0x4b2e400, 0xc0001b0600, 0x4a30c40, 0xc00012a080, 0x0, 0xc0015a5a40, 0x1000000010000, 0xc001d42f60)
10:15AM DBG     /home/runner/work/cq-provider-aws/cq-provider-aws/resources/route53_hosted_zones.go:301 +0x215
10:15AM DBG github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.callTableResolve.func1(0xc0015a5a40, 0xc00046bd80, 0x4b2e7c0, 0xc00000e048, 0x4b49a60, 0xc000488800, 0x0, 0x4b2e400, 0xc0001b0600, 0x4a30c40, ...)
10:15AM DBG received EOF, stopping recv loop err="rpc error: code = Unavailable desc = transport is closing"
10:15AM DBG     /home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:84 +0x9c
10:15AM DBG created by github.com/cloudquery/cq-provider-sdk/provider/schema.ExecutionData.callTableResolve
10:15AM DBG     /home/runner/go/pkg/mod/github.com/cloudquery/cq-provider-sdk@v0.2.1/provider/schema/execution.go:82 +0x125
10:15AM DBG plugin process exited error="exit status 2" path=/root/.cq/providers/cloudquery/aws/v0.4.4-linux_amd64 pid=103
10:15AM DBG plugin exited
```

**Comment by yevgenypats** [comment]
@Rackme should be fixed in latest release - https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.4.5

**Comment by Rackme** [comment]
@yevgenypats yes, it is, thanks. I'll take a look at the data.
