### ISSUE TITLE
Automated Release failing

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cq-provider-aws#403]
### Describe the bug

looks like more configuration is need:

https://github.com/cloudquery/terraform-aws-cloudquery/blob/main/.releaserc.json
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).
https://github.com/cloudquery/cq-provider-aws/runs/4786182839?check_suite_focus=true#step:3:43

### Expected Behavior

ci passing

### Steps to Reproduce

re run ci job

### Provider and CloudQuery version

main

**Comment by bbernays** [comment]
I think this has been fixed. Please correct me if I am wrong. @roneli @yevgenypats
