### ISSUE TITLE
Record and track AWS partition (aws, aws-cn, aws-us-gov) 

### ISSUE THREAD

**Issue by paul-e-allen** [cloudquery/cq-provider-aws#416]
### Describe the resource.

This probably doesn't need to be a first class `resource`, but AWS Partition should be tracked somwhere, like in `aws_accounts`.

### Use Case

At present, some resources don't include ARNs in their resource schema. With the current set materialized data, there is no way to create an ARN for those without making assumptions about the partition, or by grabbing the partition info from some type of resource that does materialize ARNs.

**Comment by bbernays** [comment]
Currently we only support the `aws` partition. This will be important for the future if policies differ based on partition
