### ISSUE TITLE
Support for Private Link resource

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cq-provider-aws#49]

**Comment by roneli** [comment]
Could be more specific on the resource ? Service + Type / Link to the rest API and we will get this added

**Comment by James-Quigley** [comment]
Actually think this should be covered now by https://github.com/cloudquery/cq-provider-aws/blob/dd5f58f98f091091bc0ee7999481552f8b3c3fde/resources/ec2_vpc_endpoints.go
