### ISSUE TITLE
GenerateCredentialReport is failing

### ISSUE THREAD

**Issue by Rackme** [cloudquery/cq-provider-aws#5]
I did test the `v0.1.1` release with the module `iam.users` activated. The following error appears : 

```
2021/02/18 14:40:48 operation error IAM: GenerateCredentialReport, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 57f218d2-90a0-3b8d-9b07-a816e0a559ec, api error Throttling: Rate exceeded
```

**Comment by yevgenypats** [comment]
Does it reproduce constantly on your end?

**Comment by Rackme** [comment]
You're right, again after a few time and many retries a complete fetch could be made. The `GenerateCredentialReport` is not the issue.
