### ISSUE TITLE
Foreign Key constraint cannot be implemented

### ISSUE THREAD

**Issue by James-Quigley** [cloudquery/cq-provider-aws#50]
2021/04/27 14:59:14 rpc error: code = Unknown desc = ERROR: foreign key constraint "aws_autoscaling_launch_configurati_launch_configuration_id_fkey" cannot be implemented (SQLSTATE 42804)

Might be an issue with using an incompatible version of postgres? Not able to find any requirements on PG version in the docs

**Comment by James-Quigley** [comment]
Using PostgreSQL 11.1

**Comment by roneli** [comment]
Yes we added tests sinces #34  to postgres 11. There is a migration issue from the old tables to the new ones (A lot has changed). You can either drop all tables and re-run cloudquery or just drop the specific tables doing problems and they will be recreated in this case: aws_autoscaling_launch_configuration_block_device_mappings. Tell me if you have any more issues

**Comment by James-Quigley** [comment]
Still experiencing this issue on a totally fresh DB. Using the latest version of CQ and the cq-provider-aws

**Comment by yevgenypats** [comment]
can you try run the following locally and let me know if it reproduces:

```
docker run -p 5432:5432 -e POSTGRES_PASSWORD=pass -d postgres:11.1
rm -rf .cq
cloudquery fetch --dsn 'host=localhost user=postgres password=pass DB.name=postgres port=5432'
```

**Comment by James-Quigley** [comment]
Figured it out. Seems like in the DSN you actually have to specify `dbname=mydb` instead of `DB.name=mydb` to use a different database inside the instance. When I ran against a blank db it worked fine
