### ISSUE TITLE
Not Able to Grab Global WebACL

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#518]
### Describe the bug

Only grabs regional resources.

### Expected Behavior

Should grab global WAFs that can be attached to Cloudfront distros

### Steps to Reproduce

run fetch

### Provider and CloudQuery version

all

**Comment by irmatov** [comment]
I think it can be fixed by applying Multiplexer changes from https://github.com/cloudquery/cq-provider-aws/pull/675
