### ISSUE TITLE
Unable to Resolve "model_template" in `apigateway.rest_apis`

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#519]
### Describe the bug

Error from user:
```
Resource: apigateway.rest_apis Type: Resolving Severity: Error
        Summary: column resolver "model_template" failed for table "aws_apigateway_rest_api_models"
        Resource ID: <uuid>
        Detail: [Repeated:7]
```

### Expected Behavior

should resolve data

### Steps to Reproduce

run fetch

### Provider and CloudQuery version

latest

**Comment by yevgenypats** [comment]
Fixed https://github.com/cloudquery/cq-provider-aws/commit/4f971770ba075b4cafcc81a0220d72d4b38b6e34
