### ISSUE TITLE
Remove CQ data for AWS accounts that are no longer part of the AWS Organization

### ISSUE THREAD

**Issue by paul-e-allen** [cloudquery/cq-provider-aws#520]
### Describe the resource.

Not sure how CQ data-fetching normally handles purging of "old" data. But, with AWS Organizations, it would be handy/nice if CQ would recognize that it has data for an AWS account that is no longer part of the Organization and, optionally, nuke that data.

### Use Case

Large AWS Organizations will see a regular lifecycle of account creation (or joining) and deletion (or leaving). So, in order for CQ policy checks to reflect current reality, it would be nice if CQ or the Provider would optionally delete resource data for no-longer-relevant AWS accounts so that Policy findings for the Org would no longer include findings for the no-longer-relevant accounts.

This could happen as part of the `fetch` operation, or maybe this becomes part of a new CQ CLI command like `prune` that would have options to remove data for accounts/subscriptions/projects that are no longer referenced in the `config.hcl`.

An alternative might be for Policies to be able to define the age of data that they want to use. E.g., Policy X requires data < 24 hours old. Policy Y is OK with using data up to 7 days old. Obviously this could be tackled via the SQL for the Policy, but since it would cut across all queries, it would be tedious to implement using only SQL, even with views.

**Comment by bbernays** [comment]
Thank you for this issue/reccomendation/feature request! I think that you bring up an important use case/limitation now that we are supporting more dynamic fetching via AWS Orgs where not all accounts are defined in a declarative manner.

Aside from the fact that the stale data impacts Policy Evaluations is the fact that the data remains in the database an issue for your use case?

**Comment by paul-e-allen** [comment]
To date, the fact that the DB contains data for no-longer-active accounts isn't a problem _per se_. The Policy being applied to the old data is more of a problem for my situation.

In the short term, I will probably resolve this by manually deleting the data or the relevant accounts, or by dropping and recreating the DB schema.

**Comment by ankenyr** [comment]
Pruning would be helpful for my own use case. Our inventory system will be joining cq data with other sources resulting in tables describing the entities. Keeping snapshots of those tables is planned but the cq data itself will likely not be as important and keeping those trim would be helpful to make sure we are not querying over data that no longer matters.

As for implementation, I think a prune command would be helpful. Configurable via the config.hcl file stating how old any entity can be before being removed.

**Comment by bbernays** [comment]
@paul-e-allen and @ankenyr- We have added a `prune` command to cloudquery cli. Essentially it will delete all data older than whatever value you specify. We will be tagging the release in the up coming week and releasing the documentation for it. Let us know if you have any questions or feedback about this new command!
