### ISSUE TITLE
My hosted zone has more than 100 records names 

### ISSUE THREAD

**Issue by acgoj** [cloudquery/cq-provider-aws#534]
### Describe the resource.

When the hosted zone has more than 100 records the cloudquery doesnt get all datas, is this a parameter?

### Use Case

My hosted zone has 500 records and i want to get all records.

### Additional context

the aws documentation about this command https://docs.aws.amazon.com/cli/latest/reference/route53/list-resource-record-sets.html say that get only 100 first data. But you can pass a max-item parameter to get more.

**Comment by bbernays** [comment]
@acgoj - Yes I can confirm that this is a bug. Looking into it now

**Comment by bbernays** [comment]
@acgoj - Can confirm the source of the bug. Have opened a pr to fix it

**Comment by bbernays** [comment]
We hope to release a new provider version (v0.10.11) tomorrow... In the meantime if you want to build from source on the main branch it will work

**Comment by acgoj** [comment]
Thanks @bbernays

**Comment by acgoj** [comment]
@bbernays i test this issue in v0.10.11 and continue return only 100 records, can you help me? do you want more information?

**Comment by disq** [comment]
@acgoj released `v0.10.12` which contains the fix. Thanks again for reporting.
