### ISSUE TITLE
Ensure Support for AWS::ElasticBeanstalk::*

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#621]
- [ ] AWS::ElasticBeanstalk::Application
- [ ] AWS::ElasticBeanstalk::ApplicationVersion
- [ ] AWS::ElasticBeanstalk::Environment

**Comment by shimonp21** [comment]
Adding an error I am running into related to elasticbeanstalk:
![image](https://user-images.githubusercontent.com/37939765/164225030-c32f0285-0a30-4c01-876d-6078a4588478.png)

steps to reproduce:
- authenticate with cq-playground account.
- `cloudquery init aws`
- `cloudquery fetch`

**Comment by erezrokah** [comment]
Thanks @shimonp21, looks like these resources are terminated, but somehow still available via the API:

```
aws elasticbeanstalk describe-environments --region us-east-1

{
    "Environments": [
        {
            "EnvironmentName": "<name-hidden>",
            "EnvironmentId": "*********",
            ...
        }
    ]
}

aws elasticbeanstalk terminate-environment --region us-east-1 --environment-name "<name-hidden>"

An error occurred (InvalidParameterValue) when calling the TerminateEnvironment operation: No Environment found for EnvironmentName = '<name-hidden>'.
```

When I first ran `aws elasticbeanstalk describe-environments --region us-east-1` it printed 2 environments, now it prints 1 😕  I think there might be a delay from the time the resource it destroyed until the API reflects it.

From https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.terminating.html:
>It takes a few minutes for Elastic Beanstalk to terminate the AWS resources that are running in the environment.

We should probably handle that error in the code.
