### ISSUE TITLE
CGO and cross-compiling

### ISSUE THREAD

**Issue by zscholl** [cloudquery/cq-provider-aws#7]
I was testing out the latest version of Cloudquery in AWS Lambda and I ran into a familiar issue with cross-compling CGO enabled binaries. 

When running with the AWS provider in AWS Lambda, Cloudquery pulls down the linux_amd64 AWS provider binary but it fails to run with this error message:
```
{"level":"debug","time":"2021-03-01T00:38:57Z","message":"/tmp/.cq/providers/cloudquery/aws/latest-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.cq/providers/cloudquery/aws/latest-linux-amd64)"}
```

This is a problem I've seen before with go binaries running in lambda or on an amazon linux EC2 instance, which is usually fixed by compiling the binary on amazon linux or in a docker image like: https://github.com/lambci/docker-lambda

This may affect other operating systems, particularly Alpine or others built on musl libc.

As a workaround the providers can be pre-compiled and bundled with a deployment of Cloudquery if it's running on such a system, but I wonder if the dependency on CGO could be removed from providers to make them more easily portable.

**Comment by yevgenypats** [comment]
This should be solved with:

https://github.com/cloudquery/cloudquery/releases/tag/v0.11.0
https://github.com/cloudquery/cq-provider-aws/releases/tag/v0.2.0

CGO is not needed anymore.
