### ISSUE TITLE
failed to generate cq_id for aws_iam_virtual_mfa_devices, pk field missing enable_date

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cq-provider-aws#704]
### Describe the bug

seeing the following error:

```
Resource: iam.virtual_mfa_devices Type: UNKNOWN Severity: Error
        Summary: default column "cq_id" resolver execution: failed to generate cq_id for aws_iam_virtual_mfa_devices, pk field missing enable_date
        Resource ID: arn:aws:iam::61571xxxxx:mfa/BobsMFADevice
        Detail: [Repeated:2]
```

### Expected Behavior

Not seeing the error

### Steps to Reproduce

Currently this is reproduced by fetching our aws `cq-provider-aws` account

### Provider and CloudQuery version

v0.22.2 and v0.10.16

**Comment by roneli** [comment]
Fixed in https://github.com/cloudquery/cq-provider-aws/commit/2c5b84e7575a55f8780d6e49859c8f95f2b67f99

**Comment by roneli** [comment]
Seems like an SDK issue that error type is UNKNOWN @disq

**Comment by disq** [comment]
or old cq-core, before diag.PANIC? @roneli
