### ISSUE TITLE
aws_redshift_snapshots PK Is not Unique

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#726]
### Describe the bug

PK definition is not a unique identifier across all accounts

### Expected Behavior

PK definition should be unique in order to allow for insertion

### Steps to Reproduce

Create cluster with same name in different regions

### Possible Solution

Generate an ARN field then use that instead of the identifier which is only unique in a specific region

### Provider and CloudQuery version

all

**Comment by shimonp21** [comment]
Tagging @irmatov : I see you created this resources relatively recently in https://github.com/cloudquery/cq-provider-aws/pull/645 - can you also take a look?

**Comment by bbernays** [comment]
@shimonp21 -  The issue is that we us cluster ID as the PK. Cluster ID is only unique in a specific Account + Region. So we need to use something like an ARN to guarantee uniqueness

**Comment by shimonp21** [comment]
Hmmm, in this case the issue may be more far-reaching then just the `aws_redshift_snapshots` table.

I think the `aws_redshift_clusters` (the "parent" table for this resource) Has PK:

```
Indexes:
    "aws_redshift_clusters_pk" PRIMARY KEY, btree (account_id, id)
```

**Comment by irmatov** [comment]
I'll work on fix to clusters & snapshots and I'll go over tables' PKs in the resource.
