### ISSUE TITLE
Error ingesting resources since May 21st

### ISSUE THREAD

**Issue by xino12** [cloudquery/cq-provider-aws#74]
Since May 21 we're seeing this in the logs of our ingestion job.

```
2:00AM WRN plugin failed to exit gracefully
2:00AM DBG plugin address @module=aws address=/tmp/plugin546036786 network=unix timestamp=2021-05-21T02:00:30.322Z
2:00AM DBG plugin process exited error="signal: killed" path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/aws/latest-linux-amd64 pid=99
2:00AM ERR failed to create provider plugin error="Incompatible API version with plugin. Plugin version: 2, Client versions: [1]" provider=aws version=latest
2:00AM DBG verifying provider plugin is registered pluginName=gcp version=latest
2:00AM DBG provider plugin is registered pluginName=gcp version=latest
2:00AM DBG downloading checksums file path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest.checksums.txt pluginName=gcp url=https://github.com/cloudquery/cq-provider-gcp/releases/latest/download/checksums.txt version=latest
2:00AM DBG downloading checksums signature path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest.checksums.txt pluginName=gcp url=https://github.com/cloudquery/cq-provider-gcp/releases/latest/download/checksums.txt version=latest
2:00AM DBG verifying checksums signature path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest.checksums.txt pluginName=gcp url=https://github.com/cloudquery/cq-provider-gcp/releases/latest/download/checksums.txt version=latest
2:00AM DBG getting or creating provider provider=gcp version=latest
2:00AM DBG starting plugin args=["/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest-linux-amd64"] path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest-linux-amd64
2:00AM DBG plugin started path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest-linux-amd64 pid=105
2:00AM DBG waiting for RPC address path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest-linux-amd64
2:00AM WRN plugin failed to exit gracefully
2:00AM DBG plugin address @module=gcp address=/tmp/plugin184001254 network=unix timestamp=2021-05-21T02:00:30.644Z
2:00AM DBG plugin process exited error="signal: killed" path=/home/jenkins/agent/workspace/cloudquery-ingest/.cq/providers/cloudquery/gcp/latest-linux-amd64 pid=105
2:00AM ERR failed to create provider plugin error="Incompatible API version with plugin. Plugin version: 2, Client versions: [1]" provider=gcp version=latest
```

Are you aware of this?

**Comment by roneli** [comment]
Hi @xino12 yes, we upgraded our plugin protocol, to execute protocol v2 you need a CQ 0.13.x+ if you would like to use our latest plugin versions (i.e v1) in the version of the aws provider in your config define it as v0.3.13. The major change here as well is that we changed to hcl configuration instead of yml. 

`cloudquery {
  plugin_directory = "."

  provider "aws" {
    source  = "cloudquery/cq-provider-aws"
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=pass DB.name=postgres port=5432"
  }
}

// All Provider Configurations
provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
    //accounts "<YOUR ID>"{
    // Optional. Role ARN we want to assume when accessing this account
    // role_arn = <YOUR_ROLE_ARN>
    // }
    // Optional. by default assumes all regions
    //    regions = [
    //      "us-east-1",
    //      "us-west-2",
    //    ]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = false
    // The maximum number of times that a request will be retried for failures. Defaults to 5 retry attempts.
    max_retries = 7
    // The maximum back off delay between attempts. The backoff delays exponentially with a jitter based on the number of attempts. Defaults to 60 seconds.
    max_backoff = 60
  }
  resources = [
    "autoscaling.launch_configurations",
    "cloudfront.distributions",
    "cloudfront.cache_policies",
    "cloudtrail.trails",
    "cloudwatch.alarms",
    "cloudwatchlogs.filters",
    "s3.buckets",
    "directconnect.gateways",
    "directconnect.virtual_gateways",
    "directconnect.virtual_interfaces",
    "ec2.byoip_cidrs",
    "ec2.customer_gateways",
    "ec2.flow_logs",
    "ec2.images",
    "ec2.internet_gateways",
    "ec2.nat_gateways",
    "ec2.network_acls",
    "ec2.route_tables",
    "ec2.subnets",
    "ec2.transit_gateways",
    "ec2.vpc_peering_connections",
    "ec2.vpc_endpoints",
    "ec2.vpcs",
    "ec2.instances",
    "ec2.security_groups",
    "ec2.ebs_volumes",
    "ecr.repositories",
    "efs.filesystems",
    "eks.clusters",
    "ecs.clusters",
    "elasticbeanstalk.environments",
    "elbv2.target_groups",
    "elbv2.load_balancers",
    "emr.clusters",
    "fsx.backups",
    "iam.groups",
    "iam.policies",
    "iam.password_policies",
    "iam.roles",
    "iam.users",
    "iam.virtual_mfa_devices",
    "iam.openid_connect_identity_providers",
    "iam.saml_identity_providers",
    "kms.keys",
    "organizations.accounts",
    "sns.topics",
    "sns.subscriptions",
    "rds.certificates",
    "rds.clusters",
    "rds.db_subnet_groups",
    "rds.instances",
    "redshift.clusters",
    "redshift.subnet_groups",
    "route53.reusable_delegation_sets",
    "route53.health_checks",
    "route53.hosted_zones",
    "route53.traffic_policies",
  ]
}
`

**Comment by xino12** [comment]
Thanks, is there a way to pin plugins to the previous version while I update to latest versions?

**Comment by roneli** [comment]
Yes if you put version = v0.4.3 it will only download that version and not the latest. I will add this to the docs, since its not obvious from the get go.
