### ISSUE TITLE
Shared AMIs

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-aws#753]
### Describe the resource.

AMIs can be shared across accounts. Currently we only grab AMIs that are owned by the account

### Use Case

Understand what AMIs that users can use

### Additional context

Need to ensure we mark which AMIs are shared vs owned

**Comment by bbernays** [comment]
Find shared AMIs
`aws ec2 describe-images --executable-users self`

Find self owned AMIs
`aws ec2 describe-images --executable-users self`

**Comment by andrewthetechie** [comment]
> AMIs are shared vs owned

owner_id is in the table and gives that indication, which might make this simpler to solve
