### ISSUE TITLE
SNS Topics don't get their tags

### ISSUE THREAD

**Issue by andrewthetechie** [cloudquery/cq-provider-aws#803]
### Describe the bug

aws_sns_topics table is not storing tags from the AWS SNS Topics

### Expected Behavior

Tags for SNS Topics would be stored in the cloudquery database

### Steps to Reproduce

Setup a SNS topic with a tag
Fetch SNS topic resources using cloudquery
Inspect the table schema + resources fetched and see the tag is not reflected

### Possible Solution

https://github.com/aws/aws-sdk-go-v2/blob/a1ee023a21f3cfd5c85ddae881264dbedcd1dffc/service/sns/api_op_ListTagsForResource.go
The go sdk supports the ListTagsForResource api call needed to pull tags

This would be similar to how SQS handles getting tags https://github.com/cloudquery/cq-provider-aws/blob/0173988c12a0ce54ec9865e9d8fea8ad354b3db9/resources/services/sqs/queues.go#L230

### Provider and CloudQuery version

Version: 0.22.7 Commit: fb5a1447e0851d96af0fb7d522585bf78566ff3f Date: 2022-04-19T08:55:30Z   provider "aws" {     version = "v0.10.19"   }

### Additional Context

It seems like this might just be an omission as most other AWS resources store their tags

**Comment by erezrokah** [comment]
Hi @andrewthetechie, thanks for opening the issue and a great catch!

Would you like to submit a PR for the fix?

It will require:
1. Adding the `tags` field [here](https://github.com/cloudquery/cq-provider-aws/blob/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/services/sns/topics.go#L99) similar to [here](https://github.com/cloudquery/cq-provider-aws/blob/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/services/sqs/queues.go#L155), as you mentioned
2. Add the relevant migration [here](https://github.com/cloudquery/cq-provider-aws/tree/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/provider/migrations/postgres) and [here](https://github.com/cloudquery/cq-provider-aws/tree/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/provider/migrations/timescale) to add the tags column. The names for the migration files should be `28_v0.11.2.up.sql` and `28_v0.11.2.down.sql`. You can see an example on how to add a column [here](https://github.com/cloudquery/cq-provider-aws/blob/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/provider/migrations/timescale/26_v0.10.18.up.sql#L39). The tags column type should probably be `jsonb` as [here](https://github.com/cloudquery/cq-provider-aws/blob/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/resources/provider/migrations/timescale/15_v0.10.0.up.sql#L7211). 
3. Add the code to fetch the data based on the [AWS SDK link you shared](https://github.com/aws/aws-sdk-go-v2/blob/a1ee023a21f3cfd5c85ddae881264dbedcd1dffc/service/sns/api_op_ListTagsForResource.go)
4. Run everything in [debugging mode](https://docs.cloudquery.io/docs/developers/debugging/) so see that it's working.

Bonus - add tags to our terraform files [here](https://github.com/cloudquery/cq-provider-aws/tree/5cd40bd911b6cd0bbc2c14c4edb8726e76e1b5ad/terraform/sns/modules/test) so it is added to our testing environment.

**Comment by erezrokah** [comment]
Thanks @andrewthetechie! I appreciate you looking into it. If you run into any problems let us know by commenting in the issue 🚀

**Comment by bbernays** [comment]
Closing as this issue was fixed and released
