### ISSUE TITLE
Support China Region

### ISSUE THREAD

**Issue by ywyt738** [cloudquery/cq-provider-aws#806]
### Describe the bug

When I fetch, it will report
```
unknown region: "cn-north-1"
```

### Expected Behavior

fetch success

### Steps to Reproduce

config.hcl
```
provider "aws" {
  configuration {

    regions = ["cn-north-1"]

  }
}
```

### Provider and CloudQuery version

Cloudquery: 0.22.10. AWS provider: 0.11.1

**Comment by ywyt738** [comment]
log:

8:49PM ERR failed to configure provider error="unknown region: \"cn-north-1\"" alias=aws provider=aws version=v0.11.1

**Comment by bbernays** [comment]
@ywyt738 - Thank you for this error report. We are actively looking into supporting all AWS partitions

**Comment by ywyt738** [comment]
@bbernays Thank you and wait for you good news.
