### ISSUE TITLE
assume role wrong

### ISSUE THREAD

**Issue by ywyt738** [cloudquery/cq-provider-aws#873]
### Describe the bug

The arn of role is like to "arn:\<partition\>:iam::\<account id\>:role/<rolename>".
So in China, it should be "arn:aws-cn:iam::1234567890:role/<rolename>", it is "arn:aws:iam::1234567890:role/<rolename>" now.

### Expected Behavior

assume success

### Steps to Reproduce

use org fetch in AWS China

### Provider and CloudQuery version

Cloudquery: 0.22.10. AWS provider: 0.11.4

**Comment by disq** [comment]
Hey, this should be fixed in the next release of the provider.
